apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: city-track-core
spec:
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: city-track-core
    spec:
      containers:
      - image: gustavoyama/city-track-core
        imagePullPolicy: Always
        name: city-track-core
        ports:
          - containerPort: 8080

